### ISSUE TITLE
用golang 1.18构建后拉不到配置，1.17正常。

### ISSUE THREAD

**Issue by zohu** [shima-park/agollo#72]
在本地直接run是没问题的（1.18），但是用（golang:1.18）打包后的镜像就不行了。
<img width="805" alt="image" src="https://user-images.githubusercontent.com/50687915/164217779-77ed77f8-5b8e-4e48-8bd5-55d83da869b4.png">

```
# FROM golang:latest as builder # 这个构建后就拉不到配置了，没有输出日志，golang:latest的版本是1.18的
FROM golang:1.17-alpine as builder # 这个是正常的
WORKDIR /go/delivery
ENV GO111MODULE=on
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64
ENV GOPROXY="https://goproxy.cn,direct"
COPY . .
RUN go build -o app .

FROM debian:buster-slim
COPY --from=builder /go/delivery/app .
EXPOSE 8080
CMD ["/app"]
```

**Comment by zohu** [comment]
```
func initConfigFromApollo(endpoint string) {
	remote.SetAppID(appid)
	remote.SetAgolloOptions(
		agollo.Cluster(cluster),
		agollo.AutoFetchOnCacheMiss(),
		agollo.FailTolerantOnBackupExists(),
		agollo.WithLogger(agollo.NewLogger(agollo.LoggerWriter(log.SafeWriter()))),
	)

	v := viper.New()
	v.SetConfigType("yml")
	if err := v.AddRemoteProvider("apollo", endpoint, DefaultApolloNamespace); err != nil {
		panic(err)
	}
	if err := v.ReadRemoteConfig(); err != nil {
		panic(err)
	}
	if err := v.Unmarshal(&Cfg); err != nil {
		panic(err)
	}
	log.Infof("%-10s[%s]", "配置内容概览", utils.StructToString(Cfg))
}

```

**Comment by shima-park** [comment]
我试了下，用你提供的dockerfile分别用 1.17，1.18编译了同一份代码，去读取配置，是可以读到的。
是不是其他哪里不对，例如这个地方会修改包内的一个全局变量remote.SetAppID(appid)，有没有多个地方同时初始化设置这个值，或者是其他的什么原因。

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/4186507/164371154-c6d730af-a2cc-4c8c-9c9e-e5ac15bd9918.png">

go.mod
```
module agollo

go 1.18

require (
	github.com/shima-park/agollo v1.2.12
	github.com/spf13/viper v1.11.0
)

require (
	cloud.google.com/go v0.100.2 // indirect
	cloud.google.com/go/compute v1.5.0 // indirect
	cloud.google.com/go/firestore v1.6.1 // indirect
	github.com/armon/go-metrics v0.3.10 // indirect
	github.com/bketelsen/crypt v0.0.4 // indirect
	github.com/coreos/go-semver v0.3.0 // indirect
	github.com/fatih/color v1.13.0 // indirect
	github.com/fsnotify/fsnotify v1.5.1 // indirect
	github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da // indirect
	github.com/golang/protobuf v1.5.2 // indirect
	github.com/google/go-cmp v0.5.7 // indirect
	github.com/googleapis/gax-go/v2 v2.3.0 // indirect
	github.com/hashicorp/consul/api v1.12.0 // indirect
	github.com/hashicorp/go-cleanhttp v0.5.2 // indirect
	github.com/hashicorp/go-hclog v1.2.0 // indirect
	github.com/hashicorp/go-immutable-radix v1.3.1 // indirect
	github.com/hashicorp/go-rootcerts v1.0.2 // indirect
	github.com/hashicorp/golang-lru v0.5.4 // indirect
	github.com/hashicorp/hcl v1.0.0 // indirect
	github.com/hashicorp/serf v0.9.7 // indirect
	github.com/json-iterator/go v1.1.12 // indirect
	github.com/magiconair/properties v1.8.6 // indirect
	github.com/mattn/go-colorable v0.1.12 // indirect
	github.com/mattn/go-isatty v0.0.14 // indirect
	github.com/mitchellh/go-homedir v1.1.0 // indirect
	github.com/mitchellh/mapstructure v1.4.3 // indirect
	github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd // indirect
	github.com/modern-go/reflect2 v1.0.2 // indirect
	github.com/pelletier/go-toml v1.9.4 // indirect
	github.com/pelletier/go-toml/v2 v2.0.0-beta.8 // indirect
	github.com/spf13/afero v1.8.2 // indirect
	github.com/spf13/cast v1.4.1 // indirect
	github.com/spf13/jwalterweatherman v1.1.0 // indirect
	github.com/spf13/pflag v1.0.5 // indirect
	github.com/subosito/gotenv v1.2.0 // indirect
	go.etcd.io/etcd/api/v3 v3.5.2 // indirect
	go.etcd.io/etcd/client/pkg/v3 v3.5.2 // indirect
	go.etcd.io/etcd/client/v2 v2.305.2 // indirect
	go.opencensus.io v0.23.0 // indirect
	golang.org/x/crypto v0.0.0-20220411220226-7b82a4e95df4 // indirect
	golang.org/x/net v0.0.0-20220412020605-290c469a71a5 // indirect
	golang.org/x/oauth2 v0.0.0-20220411215720-9780585627b5 // indirect
	golang.org/x/sys v0.0.0-20220412211240-33da011f77ad // indirect
	golang.org/x/text v0.3.7 // indirect
	golang.org/x/xerrors v0.0.0-20220411194840-2f41105eb62f // indirect
	google.golang.org/api v0.74.0 // indirect
	google.golang.org/appengine v1.6.7 // indirect
	google.golang.org/genproto v0.0.0-20220407144326-9054f6ed7bac // indirect
	google.golang.org/grpc v1.45.0 // indirect
	google.golang.org/protobuf v1.28.0 // indirect
	gopkg.in/ini.v1 v1.66.4 // indirect
	gopkg.in/yaml.v2 v2.4.0 // indirect
	gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b // indirect
)

```

```
package main

import (
	"fmt"

	"github.com/shima-park/agollo"
	remote "github.com/shima-park/agollo/viper-remote"
	"github.com/spf13/viper"
)

func main() {
	remote.SetAppID("SampleApp")
	remote.SetAgolloOptions(
		agollo.Cluster("default"),
		agollo.AutoFetchOnCacheMiss(),
		agollo.FailTolerantOnBackupExists(),
	)

	v := viper.New()
	v.SetConfigType("yml")
	if err := v.AddRemoteProvider("apollo", "192.168.0.102:8080", "test.yml"); err != nil {
		panic(err)
	}
	if err := v.ReadRemoteConfig(); err != nil {
		panic(err)
	}
	var conf struct {
		Name string `yaml:"name"`
	}
	if err := v.Unmarshal(&conf); err != nil {
		panic(err)
	}
	fmt.Printf("%-10s[%+v]\n", "配置内容概览", conf)
}

```

<img width="707" alt="image" src="https://user-images.githubusercontent.com/4186507/164371060-de718ef6-d46f-4073-9bc9-5cc1e1cd1192.png">

**Comment by zohu** [comment]
做了一个最小复现库，https://github.com/hhcool/docker-agollo-test.git

**Comment by zohu** [comment]
```
2022-04-21 07:12:51.396 INFO    config/config.go:48     使用远程配置    [https://apollo-dev.xxx.com]
2022-04-21 07:12:51.397 INFO    config/config.go:50     远程配置项目    [loc]
2022-04-21 07:12:51.397 INFO    config/config.go:52     远程配置集群    [default]
2022-04-21 07:12:51.397 INFO    config/config.go:64     远程配置空间    [e-msr-file.yml]
2022-04-21 07:12:51.397 INFO    config/config.go:68     开始拉取配置    [请等待...]
2022-04-21 07:12:51.410 INFO    config/config.go:75     配置内容概览    [{"Serve":{"Name":"","Port":0,"Env":"","Client":"","MainDate":"","MainUrl":""},"Middleware":{"Cors":false,"Timeout":0,"RateLimit":0,"SizeLimit":0,"Whitelist":null},"File":{"Type":"","AccessKey":"","SecretKey":"","Endpoint":"","Bucket":"","Path":"","ExportExp":""},"Redis":{"Host":null,"Password":""},"Mysql":{"Host":"","Port":"","UserName":"","Password":"","DataBase":"","Config":""},"Logger":{"LenBody":0,"LenResponse":0,"GoutDebug":false,"Path":"","MaxAge":0}}]
```
```
serve:
    name: e-msr-file
    port: 8080
    env: prod
    client: 
    mainDate: 2022-04-17
    mainUrl: 

middleware:
    cors: true
    timeout: 180s
    rateLimit: 0
    sizeLimit: 1024e6
    whitelist:
        - file
        - v1

file:
    type: oss
    accessKey: 
    secretKey: 
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucket: bty-file
    path: bty/edp/uat
    exportExp: 3h
redis:
    host:
        - redis-0.redis.edp-bty.svc.cluster.local:6379
        - redis-1.redis.edp-bty.svc.cluster.local:6379
        - redis-2.redis.edp-bty.svc.cluster.local:6379
        - redis-3.redis.edp-bty.svc.cluster.local:6379
        - redis-4.redis.edp-bty.svc.cluster.local:6379
        - redis-5.redis.edp-bty.svc.cluster.local:6379
    password: Best.2020

mysql:
    host: mysql.edp-bty.svc.cluster.local
    port: 3306
    username: 
    password: 
    database: bty-file
    config: charset=utf8mb4&parseTime=True&loc=Local

logger:
    lenbody: 4096
    lenresponse: 4096
    goutdebug: true
    path: log
    maxage: 30
```
